[package]
name = "roastedornot"
version = "0.1.0"
authors = ["rgrossemy"]
edition = "2019"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
reqwest = "0.9.20"
rouille = "3.0.0"
